### ISSUE TITLE
Mouse focus

### ISSUE THREAD

**Issue by EGiorgisCPNV** [samuelroland/openDevApps#1]
Impossible to finalize the creation of a link if you check or uncheck the checkbox with a mouse click for the question of a local or remote rest, because the focus does not work anymore

**Comment by samuelroland** [comment]
Hey. Thanks for this bug report. In my manual tests, I never used the mouse to check/uncheck the checkbox. I tried to reproduce the bug and I saw that the focus on the checkbox is kept if the mouse doesn't click in other places (test with Firefox 86.0.1 on Windows), BUT that on MacOS Catalina with same version of Firefox, the focus is left in all cases when using the mouse... This difference between MacOS and Windows surprised me...

I will try to find an easy solution to fix this before the v1.0.

**Comment by samuelroland** [comment]
Hey, 
I have reflected a bit to this bug. The quick fix is to focus explicitly the checkbox on mouse click, to avoid lose of focus. The long fix is to enable keyup event listen on the whole extension (to be sure that the Enter will always be possible to hit, even if the mouse click outside of the input), but this other solution imply that the other fields have to be disabled (else the extension is not able to know which action is wanted (link or category creation)).

I will implement the quick fix for v1.0 and we will see later if another strategy is needed.

**Comment by samuelroland** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/47849646/112548934-4b80ce00-8dbd-11eb-99a2-8889a95ae963.png">
It's fixed ! Here eb638a9e5e4657cd80e45e6c662df215c889b5dc. I tested it on MacOS with mouse click and the focus is kept.

**Comment by samuelroland** [comment]
Will be naturally available for v1.0...
